[package]
name = "mangsh"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
crossterm = "0.29.0"
dirs = "6.0.0"
ratatui = { version = "0.29.0", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.8.19"
